"""The lab's reach and avoidance problems rebuilt from library components, for the golden tests.

The lab's model has a constant mass matrix, diagonal stiffness and damping, and no gravity; its
elements are springs and dampers attached at points of the arm. The data come from the fixtures
generated by running the lab's own code (``tests/data/optimization.{npz,json}``).
"""

import json
from pathlib import Path

import casadi as ca
import numpy as np

import virtualmodelcontrol as vmc
from virtualmodelcontrol import optimization as opt
from virtualmodelcontrol.robots import helyx

DATA = Path(__file__).parent / "data"
ARRAYS = np.load(DATA / "optimization.npz")
INFO = json.loads((DATA / "optimization.json").read_text(encoding="utf-8"))
COMMON = INFO["common"]
SECTION_RADIUS = helyx.SECTION_RADIUS
SIGN = helyx.ENCODER_SIGN["145-290-290"]  # the lab's motor torques are SIGN times the library's


def lab_robot():
    """The arm as the lab models it: constant M, diagonal K and D, tendons, no gravity."""
    robot = vmc.Mechanism("arm", model=helyx.model("145-290-290"), actuation=helyx.tendons())
    delta = robot.joint(slice(0, 9))
    robot.add("inertia", vmc.Inertance(delta, ARRAYS["M0"]))
    robot.add("stiffness", vmc.LinearSpring(delta, vmc.Param("stiffness", ARRAYS["K"])))
    robot.add("damping", vmc.LinearDamper(delta, vmc.Param("damping", ARRAYS["D"])))
    return robot


def hold_system(robot):
    """The linear spring and damper that hold the arm at the start."""
    drag = COMMON["drag"]
    hold = vmc.Mechanism("hold")
    point = robot.point(s=drag["s"])
    hold.add("drag", vmc.LinearSpring(point - drag["reference"], drag["stiffness"]))
    hold.add("damper", vmc.LinearDamper(point, drag["damping"]))
    return vmc.VirtualMechanismSystem(robot, hold)


def new_controller(robot, case, scenario):
    """The TanH spring toward the target and two Gaussian springs per obstacle, as the lab sets
    them up for a case: A frees the gains, B the placement, C both."""
    c = COMMON
    gains, placement = case in "AC", case in "BC"
    ctrl = vmc.Mechanism("ctrl")

    def point(s):
        bounds = tuple(c["s_bounds"]) if placement else (0.0, 1.0)
        return robot.point(s=vmc.Param("s", s, bounds=bounds, scope="episode"))

    tip = point(1.0)
    goal = vmc.Ref("goal", 3, c["target"])
    k = vmc.Param("stiffness", c["tanh"]["k_init"], bounds=tuple(c["tanh"]["k_bounds"]))
    ctrl.add("tanh", vmc.TanhSpring(tip - goal, k, c["tanh"]["max_force"]))
    ctrl.add("tanh_damper", vmc.LinearDamper(tip, c["tanh"]["damping"]))
    free = ["ctrl.tanh.stiffness"] * gains + ["ctrl.tanh.s"] * placement
    parameters = ["ctrl.tanh.goal"]
    for j, obstacle in enumerate(scenario["obstacles"]):
        center = vmc.Ref(f"center{j + 1}", 3, obstacle["center"])
        for i, s in enumerate(c["gauss"]["s"]):
            name = f"gauss{j + 1}_{i + 1}"
            strength = vmc.Param(
                "strength", c["gauss"]["strength"], bounds=tuple(c["gauss"]["strength_bounds"])
            )
            at = point(s)
            ctrl.add(name, vmc.GaussianSpring(at - center, strength, c["gauss"]["sigma"]))
            ctrl.add(f"{name}_damper", vmc.LinearDamper(at, c["gauss"]["damping"]))
            free += [f"ctrl.{name}.strength"] * gains + [f"ctrl.{name}.s"] * placement
        parameters.append(f"ctrl.gauss{j + 1}_1.center{j + 1}")
    return ctrl, free, parameters


def bending_coordinate(delta):
    """Squared bending of each section, Dx² + Dy², the lab's smooth form of its angle limit."""

    def fn(y):
        return ca.vertcat(*[y[3 * i] ** 2 + y[3 * i + 1] ** 2 for i in range(3)])

    return vmc.Custom(fn, [delta], dim=3)


def clearance_coordinate(robot, center, radius):
    """Distance of the backbone samples to the obstacle's surface, with the lab's smoothing."""
    points = [robot.point(s=float(s)) for s in np.linspace(0.0, 1.0, COMMON["backbone_samples"])]

    def fn(*ps):
        return ca.vertcat(*[ca.sqrt(ca.sumsqr(p - np.asarray(center)) + 1e-9) - radius for p in ps])

    return vmc.Custom(fn, points, dim=len(points))


def lab_problem(name, options=None, scales=None):
    """Problem, the free names and the references of a fixture scenario (as in ``INFO``)."""
    c, sc = COMMON, INFO["scenarios"][name]
    robot = lab_robot()
    ctrl, free, parameters = new_controller(robot, sc["case"], sc)
    system = vmc.VirtualMechanismSystem(robot, ctrl)
    problem = opt.Problem(system, options=options)
    problem.add(
        opt.Collocation(
            c["delta0"],
            horizon=c["transition"] + c["settle"],
            nodes=c["nodes"],
            initial=hold_system(robot),
            transition=c["transition"],
            scales=c["scales"] if scales is None else scales,
        )
    )
    problem.free(*free)
    problem.parameter(*parameters)
    problem.add(opt.Effort(sc["w_effort"]))
    reach = robot.point(s=1.0) - c["target"]
    problem.add(opt.Cost(reach, c["w_reach"], t_from=c["transition"], name="reach"))
    delta0 = np.asarray(c["delta0"])
    start = np.hypot(delta0[0::3], delta0[1::3]) / SECTION_RADIUS
    limit = SECTION_RADIUS * np.maximum(np.radians(c["max_bend_deg"]), start)
    problem.add(
        opt.Bound(bending_coordinate(robot.joint(slice(0, 9))), upper=limit**2, name="bending")
    )
    for j, obstacle in enumerate(sc["obstacles"]):
        coordinate = clearance_coordinate(robot, obstacle["center"], obstacle["radius"])
        problem.add(opt.Bound(coordinate, lower=c["clearance"], name=f"obstacle{j + 1}"))
    refs = {"ctrl.tanh.goal": c["target"]}
    for j, obstacle in enumerate(sc["obstacles"]):
        refs[f"ctrl.gauss{j + 1}_1.center{j + 1}"] = obstacle["center"]
    return problem, free, refs


def names(free, element):
    """The library's names for the lab's free values of an element ('tanh', 'gauss1_1', ...)."""
    return {part: f"ctrl.{element}.{part}" for part in ("s", "stiffness", "strength")}
